# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"alt": "charts.ipynb",
         "Chart": "charts.ipynb",
         "confusion_matrix": "charts.ipynb",
         "CM": "charts.ipynb",
         "get_console": "logging.ipynb",
         "console": "logging.ipynb",
         "print": "logging.ipynb",
         "render": "logging.ipynb",
         "logger": "logging.ipynb",
         "Debug": "logging.ipynb",
         "Info": "logging.ipynb",
         "Warn": "logging.ipynb",
         "Excep": "logging.ipynb",
         "reset_logger_width": "logging.ipynb",
         "train_test_split": "sklegos.ipynb",
         "ColumnSelector": "sklegos.ipynb",
         "transform": "sklegos.ipynb",
         "GroupedEstimator": "sklegos.ipynb",
         "GroupedPredictor": "sklegos.ipynb",
         "EstimatorTransformer": "sklegos.ipynb",
         "MakeFrame": "sklegos.ipynb",
         "ImputeMissingValues": "sklegos.ipynb",
         "LambdaTransformer": "sklegos.ipynb",
         "Cat2Num": "sklegos.ipynb",
         "SplitDateColumn": "sklegos.ipynb"}

modules = ["charts.py",
           "logger.py",
           "sklegos.py"]

doc_url = "https://sizhky.github.io/torch_snippets/"

git_url = "https://github.com/sizhky/torch_snippets/tree/master/"

def custom_doc_links(name): return None
