# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"alt": "charts.ipynb",
         "Chart": "charts.ipynb"}

modules = ["charts.py"]

doc_url = "https://sizhky.github.io/torch_snippets/"

git_url = "https://github.com/sizhky/torch_snippets/tree/master/"

def custom_doc_links(name): return None
