# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/registry.ipynb.

# %% auto 0
__all__ = ['Config', 'AttrDict', 'registry', 'parse', 'parse_and_resolve', 'parse_string']

# %% ../nbs/registry.ipynb 2
from .markup import Config, AttrDict
from .thinc_parser.parser import registry

# %% ../nbs/registry.ipynb 3
Config = Config
AttrDict = AttrDict
registry = registry


def parse(file):
    return AttrDict(Config().from_disk(file))


def parse_and_resolve(file):
    return AttrDict(registry.resolve(Config().from_disk(file)))


def parse_string(string):
    return AttrDict(Config().from_str(string))
